"""
Brain Tumor Detection - 4 Class CNN
====================================

Classes:
    0 = Glioma
    1 = No Tumor
    2 = Pituitary
    3 = Meningioma

Dataset:
    Training:
        Glioma       = 1400
        No Tumor     = 1400
        Pituitary    = 1400
        Meningioma   = 1400
        Total        = 5600

    Testing:
        Glioma       = 400
        No Tumor     = 400
        Pituitary    = 400
        Meningioma   = 400
        Total        = 1600

IMPORTANT:
    - Training is performed ONLY on training/ (with a validation split
      carved out of it -- see FIX #1 below)
    - Final evaluation is performed ONLY on testing/
    - Training images are NOT used for final prediction/evaluation
    - No external/demo images are downloaded

--- FIXES vs. the original version ---------------------------------------

FIX #1 - CRITICAL BUG: model.fit() was called with callbacks monitoring
    "val_loss"/"val_accuracy" (EarlyStopping, ReduceLROnPlateau,
    ModelCheckpoint) but NO validation_data was ever passed in. Keras does
    not error on this -- it silently skips those callbacks entirely, since
    there is nothing for them to monitor. In practice this meant:
      - EarlyStopping never triggered -> trained the full 30 epochs
        regardless of overfitting
      - ReduceLROnPlateau never fired -> learning rate never adapted
      - ModelCheckpoint never saved a "best" model -> the fully-trained,
        unregularized model was what got evaluated
    Fixed by using ImageDataGenerator(validation_split=...) with
    flow_from_directory(subset="training"/"validation"), carving a real
    validation set out of the training folder while keeping testing/
    completely untouched for final evaluation, and passing that
    validation generator into model.fit().

FIX #2 - Transfer learning (EfficientNetB0, ImageNet weights) instead of a
    from-scratch CNN. With no working validation signal, the original
    model overfit toward the "easy" classes (Glioma/No Tumor/Pituitary,
    which separate cleanly) while never being corrected on the harder
    Meningioma-vs-Glioma boundary. A pretrained backbone starts with much
    stronger general visual features, which typically helps most on
    exactly this kind of fine-grained, hard-to-separate class pair.

FIX #3 - Two-phase training: (a) frozen backbone, train new classifier
    head only; (b) unfreeze top backbone layers, fine-tune at a much
    lower learning rate. Both phases now have real EarlyStopping /
    ReduceLROnPlateau / ModelCheckpoint behavior since validation_data is
    correctly supplied throughout.

NOTE ON DATA QUALITY: this folder layout (glioma/notumor/pituitary/
    meningioma, 1400 each) matches a well-known public Kaggle brain-tumor
    MRI dataset. Users of that dataset have repeatedly reported
    Meningioma being the hardest class to separate from Glioma, including
    some images flagged as ambiguous/mislabeled in community discussion.
    If accuracy on Meningioma is still weak after these fixes, it's worth
    opening test_predictions.csv (already generated by this script),
    filtering to actual_class == "meningioma" with predicted_class ==
    "glioma", and visually spot-checking a handful of those MRI slices
    yourself -- that's the fastest way to tell "model needs more
    work" apart from "some of these images are genuinely
    ambiguous/mislabeled."
"""

import os
import random
import warnings

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from tensorflow.keras import layers, models
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.applications.efficientnet import preprocess_input
from tensorflow.keras.preprocessing.image import ImageDataGenerator

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    cohen_kappa_score
)


# ============================================================
# 1. CONFIGURATION
# ============================================================

# CHANGE THIS PATH
DATASET_DIR = r"E:\my-data\Opencv-job-stuff\projects-for-programming-learning\portfolio-projects\brain-mri\data"

TRAIN_DIR = os.path.join(DATASET_DIR, "training")
TEST_DIR = os.path.join(DATASET_DIR, "testing")

OUTPUT_DIR = os.path.join(DATASET_DIR, "output")

IMG_SIZE = (224, 224)
BATCH_SIZE = 32
HEAD_EPOCHS = 15         # phase 1: train new classifier head, backbone frozen
FINE_TUNE_EPOCHS = 25    # phase 2: fine-tune top backbone layers
FINE_TUNE_AT = 200       # unfreeze EfficientNetB0 layers from this index onward
VALIDATION_SPLIT = 0.15  # carved out of training/ only -- testing/ stays untouched

SEED = 42

CLASS_NAMES = [
    "glioma",
    "notumor",
    "pituitary",
    "meningioma"
]

NUM_CLASSES = len(CLASS_NAMES)


# ============================================================
# 2. REPRODUCIBILITY
# ============================================================

os.environ["PYTHONHASHSEED"] = str(SEED)

random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

warnings.filterwarnings("ignore")

os.makedirs(OUTPUT_DIR, exist_ok=True)


# ============================================================
# 3. CHECK DATASET
# ============================================================

def check_dataset():

    print("\n" + "=" * 70)
    print("CHECKING DATASET")
    print("=" * 70)

    if not os.path.exists(TRAIN_DIR):
        raise FileNotFoundError(
            f"\nTraining folder not found:\n{TRAIN_DIR}\n"
        )

    if not os.path.exists(TEST_DIR):
        raise FileNotFoundError(
            f"\nTesting folder not found:\n{TEST_DIR}\n"
        )

    print("\nTraining folder:")
    print(TRAIN_DIR)

    print("\nTesting folder:")
    print(TEST_DIR)

    print("\nTraining image counts:")

    train_total = 0

    for class_name in CLASS_NAMES:

        class_path = os.path.join(TRAIN_DIR, class_name)

        if not os.path.exists(class_path):
            raise FileNotFoundError(
                f"Missing training class folder:\n{class_path}"
            )

        count = len([
            f for f in os.listdir(class_path)
            if f.lower().endswith(
                (".jpg", ".jpeg", ".png", ".bmp", ".webp")
            )
        ])

        train_total += count

        print(f"  {class_name:15s}: {count}")

    print(f"  {'TOTAL':15s}: {train_total}")

    print("\nTesting image counts:")

    test_total = 0

    for class_name in CLASS_NAMES:

        class_path = os.path.join(TEST_DIR, class_name)

        if not os.path.exists(class_path):
            raise FileNotFoundError(
                f"Missing testing class folder:\n{class_path}"
            )

        count = len([
            f for f in os.listdir(class_path)
            if f.lower().endswith(
                (".jpg", ".jpeg", ".png", ".bmp", ".webp")
            )
        ])

        test_total += count

        print(f"  {class_name:15s}: {count}")

    print(f"  {'TOTAL':15s}: {test_total}")

    print("\nDataset check completed.")


# ============================================================
# 4. DATA GENERATORS
# ============================================================

def create_data_generators():

    print("\n" + "=" * 70)
    print("CREATING DATA GENERATORS")
    print("=" * 70)

    # FIX #1: validation_split carves a held-out set OUT OF training/ only.
    # This is what makes val_loss/val_accuracy actually exist during
    # training, so EarlyStopping/ReduceLROnPlateau/ModelCheckpoint (which
    # monitor those metrics) can actually function -- previously they had
    # nothing to monitor and were silently doing nothing all 30 epochs.
    #
    # preprocess_input (EfficientNet's expected preprocessing) replaces the
    # manual rescale=1/255 -- EfficientNet expects its own specific input
    # scaling, not plain 0-1 normalization.
    train_datagen = ImageDataGenerator(
        preprocessing_function=preprocess_input,

        rotation_range=10,

        width_shift_range=0.10,

        height_shift_range=0.10,

        zoom_range=0.10,

        horizontal_flip=True,

        validation_split=VALIDATION_SPLIT
    )

    # NO augmentation for validation or testing -- only EfficientNet's
    # required preprocessing.
    eval_datagen = ImageDataGenerator(
        preprocessing_function=preprocess_input,

        validation_split=VALIDATION_SPLIT
    )

    test_datagen = ImageDataGenerator(
        preprocessing_function=preprocess_input
    )

    train_generator = train_datagen.flow_from_directory(
        TRAIN_DIR,

        target_size=IMG_SIZE,

        batch_size=BATCH_SIZE,

        class_mode="sparse",

        classes=CLASS_NAMES,

        subset="training",

        shuffle=True,

        seed=SEED
    )

    val_generator = eval_datagen.flow_from_directory(
        TRAIN_DIR,

        target_size=IMG_SIZE,

        batch_size=BATCH_SIZE,

        class_mode="sparse",

        classes=CLASS_NAMES,

        subset="validation",

        shuffle=False,

        seed=SEED
    )

    test_generator = test_datagen.flow_from_directory(
        TEST_DIR,

        target_size=IMG_SIZE,

        batch_size=BATCH_SIZE,

        class_mode="sparse",

        classes=CLASS_NAMES,

        shuffle=False
    )

    print("\nClass mapping:")

    print(train_generator.class_indices)

    print("\nTraining samples:",
          train_generator.samples)

    print("Validation samples:",
          val_generator.samples,
          f"({VALIDATION_SPLIT:.0%} of training/, held out from training)")

    print("Testing samples:",
          test_generator.samples)

    return train_generator, val_generator, test_generator


# ============================================================
# 5. BUILD CNN MODEL
# ============================================================

def build_model():

    print("\n" + "=" * 70)
    print("BUILDING MODEL (EfficientNetB0 transfer learning)")
    print("=" * 70)

    base_model = EfficientNetB0(
        input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3),
        include_top=False,
        weights="imagenet"
    )
    base_model.trainable = False  # frozen for phase 1

    inputs = layers.Input(shape=(IMG_SIZE[0], IMG_SIZE[1], 3))
    x = base_model(inputs, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dropout(0.3)(x)
    x = layers.Dense(128, activation="relu")(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.4)(x)

    # 4 classes
    outputs = layers.Dense(NUM_CLASSES, activation="softmax")(x)

    model = models.Model(inputs, outputs)

    model.compile(

        optimizer=tf.keras.optimizers.Adam(
            learning_rate=0.0001
        ),

        loss="sparse_categorical_crossentropy",

        metrics=[
            "accuracy"
        ]
    )

    model.summary()

    return model, base_model


# ============================================================
# 6. TRAIN MODEL
# ============================================================

def train_model(
    model,
    base_model,
    train_generator,
    val_generator
):

    print("\n" + "=" * 70)
    print("STARTING TRAINING")
    print("=" * 70)

    # FIX #1: val_generator is now real held-out data from training/
    # (never from testing/), so these callbacks actually have something
    # to monitor -- previously val_loss/val_accuracy did not exist in the
    # logs at all and these callbacks silently did nothing for 30 epochs.
    callbacks = [

        tf.keras.callbacks.EarlyStopping(
            monitor="val_loss",
            patience=6,
            restore_best_weights=True,
            verbose=1
        ),

        tf.keras.callbacks.ReduceLROnPlateau(
            monitor="val_loss",
            factor=0.5,
            patience=3,
            min_lr=1e-7,
            verbose=1
        ),

        tf.keras.callbacks.ModelCheckpoint(
            os.path.join(
                OUTPUT_DIR,
                "best_brain_tumor_model.keras"
            ),

            monitor="val_accuracy",

            save_best_only=True,

            verbose=1
        )
    ]

    # --- Phase 1: train new head only, backbone frozen -----------------
    print("\n=== Phase 1: training classifier head (backbone frozen) ===")
    history1 = model.fit(

        train_generator,

        epochs=HEAD_EPOCHS,

        validation_data=val_generator,

        callbacks=callbacks,

        verbose=1
    )

    # --- Phase 2: unfreeze top backbone layers, fine-tune at low LR ----
    print("\n=== Phase 2: fine-tuning top backbone layers ===")
    base_model.trainable = True
    for layer in base_model.layers[:FINE_TUNE_AT]:
        layer.trainable = False

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    history2 = model.fit(

        train_generator,

        epochs=HEAD_EPOCHS + FINE_TUNE_EPOCHS,

        initial_epoch=len(history1.epoch),

        validation_data=val_generator,

        callbacks=callbacks,

        verbose=1
    )

    # Merge both phases' histories into one for the training curve plots
    history = history1
    for key in history.history:
        history.history[key] += history2.history.get(key, [])

    return history


# ============================================================
# 7. SAVE TRAINING CURVES
# ============================================================

def save_training_curves(history):

    print("\nSaving training curves...")

    # Accuracy
    plt.figure(figsize=(8, 6))

    plt.plot(
        history.history["accuracy"],
        label="Training Accuracy"
    )

    if "val_accuracy" in history.history:
        plt.plot(
            history.history["val_accuracy"],
            label="Validation Accuracy"
        )

    plt.xlabel("Epoch")
    plt.ylabel("Accuracy")

    plt.title(
        "Training vs Validation Accuracy"
    )

    plt.legend()

    plt.grid(alpha=0.3)

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_DIR,
            "training_accuracy.png"
        ),
        dpi=200
    )

    plt.close()

    # Loss
    plt.figure(figsize=(8, 6))

    plt.plot(
        history.history["loss"],
        label="Training Loss"
    )

    if "val_loss" in history.history:
        plt.plot(
            history.history["val_loss"],
            label="Validation Loss"
        )

    plt.xlabel("Epoch")
    plt.ylabel("Loss")

    plt.title(
        "Training vs Validation Loss"
    )

    plt.legend()

    plt.grid(alpha=0.3)

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_DIR,
            "training_loss.png"
        ),
        dpi=200
    )

    plt.close()

    print("Training curves saved.")


# ============================================================
# 8. TEST-ONLY PREDICTION
# ============================================================

def predict_test_set(
    model,
    test_generator
):

    print("\n" + "=" * 70)
    print("PREDICTING TEST SET ONLY")
    print("=" * 70)

    # Make absolutely sure prediction starts from first test image
    test_generator.reset()

    probabilities = model.predict(
        test_generator,
        verbose=1
    )

    predictions = np.argmax(
        probabilities,
        axis=1
    )

    true_labels = test_generator.classes

    return (
        true_labels,
        predictions,
        probabilities
    )


# ============================================================
# 9. CALCULATE METRICS
# ============================================================

def calculate_metrics(
    true_labels,
    predictions
):

    print("\n" + "=" * 70)
    print("TEST SET PERFORMANCE")
    print("=" * 70)

    # --------------------------------------------------------
    # Accuracy
    # --------------------------------------------------------

    accuracy = accuracy_score(
        true_labels,
        predictions
    )

    # --------------------------------------------------------
    # Precision
    # --------------------------------------------------------

    precision_macro = precision_score(
        true_labels,
        predictions,
        average="macro",
        zero_division=0
    )

    precision_weighted = precision_score(
        true_labels,
        predictions,
        average="weighted",
        zero_division=0
    )

    # --------------------------------------------------------
    # Recall
    # --------------------------------------------------------

    recall_macro = recall_score(
        true_labels,
        predictions,
        average="macro",
        zero_division=0
    )

    recall_weighted = recall_score(
        true_labels,
        predictions,
        average="weighted",
        zero_division=0
    )

    # --------------------------------------------------------
    # F1
    # --------------------------------------------------------

    f1_macro = f1_score(
        true_labels,
        predictions,
        average="macro",
        zero_division=0
    )

    f1_weighted = f1_score(
        true_labels,
        predictions,
        average="weighted",
        zero_division=0
    )

    # --------------------------------------------------------
    # MCC
    # --------------------------------------------------------

    mcc = matthews_corrcoef(
        true_labels,
        predictions
    )

    # --------------------------------------------------------
    # Cohen's Kappa
    # --------------------------------------------------------

    kappa = cohen_kappa_score(
        true_labels,
        predictions
    )

    # --------------------------------------------------------
    # Print metrics
    # --------------------------------------------------------

    print(
        f"\nAccuracy              : {accuracy:.4f}"
    )

    print(
        f"Macro Precision       : {precision_macro:.4f}"
    )

    print(
        f"Weighted Precision    : {precision_weighted:.4f}"
    )

    print(
        f"Macro Recall          : {recall_macro:.4f}"
    )

    print(
        f"Weighted Recall       : {recall_weighted:.4f}"
    )

    print(
        f"Macro F1-Score        : {f1_macro:.4f}"
    )

    print(
        f"Weighted F1-Score     : {f1_weighted:.4f}"
    )

    print(
        f"Matthews Corr. Coef.  : {mcc:.4f}"
    )

    print(
        f"Cohen's Kappa         : {kappa:.4f}"
    )

    # --------------------------------------------------------
    # Classification report
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("PER-CLASS CLASSIFICATION REPORT")
    print("-" * 70)

    report = classification_report(
        true_labels,
        predictions,
        target_names=[
            "Glioma",
            "No Tumor",
            "Pituitary",
            "Meningioma"
        ],
        digits=4,
        zero_division=0
    )

    print(report)

    # Save report
    with open(
        os.path.join(
            OUTPUT_DIR,
            "classification_report.txt"
        ),
        "w"
    ) as f:

        f.write(
            "BRAIN TUMOR CLASSIFICATION REPORT\n"
        )

        f.write(
            "=" * 70 + "\n\n"
        )

        f.write(
            f"Accuracy              : {accuracy:.4f}\n"
        )

        f.write(
            f"Macro Precision       : {precision_macro:.4f}\n"
        )

        f.write(
            f"Weighted Precision    : {precision_weighted:.4f}\n"
        )

        f.write(
            f"Macro Recall          : {recall_macro:.4f}\n"
        )

        f.write(
            f"Weighted Recall       : {recall_weighted:.4f}\n"
        )

        f.write(
            f"Macro F1-Score        : {f1_macro:.4f}\n"
        )

        f.write(
            f"Weighted F1-Score     : {f1_weighted:.4f}\n"
        )

        f.write(
            f"Matthews Corr. Coef.  : {mcc:.4f}\n"
        )

        f.write(
            f"Cohen's Kappa         : {kappa:.4f}\n\n"
        )

        f.write(
            report
        )

    return {
        "accuracy": accuracy,
        "macro_precision": precision_macro,
        "weighted_precision": precision_weighted,
        "macro_recall": recall_macro,
        "weighted_recall": recall_weighted,
        "macro_f1": f1_macro,
        "weighted_f1": f1_weighted,
        "mcc": mcc,
        "cohen_kappa": kappa
    }


# ============================================================
# 10. CONFUSION MATRIX
# ============================================================

def save_confusion_matrix(
    true_labels,
    predictions
):

    print("\nSaving confusion matrix...")

    cm = confusion_matrix(
        true_labels,
        predictions
    )

    plt.figure(
        figsize=(8, 7)
    )

    sns.heatmap(
        cm,
        annot=True,
        fmt="d",
        cmap="Blues",
        xticklabels=[
            "Glioma",
            "No Tumor",
            "Pituitary",
            "Meningioma"
        ],
        yticklabels=[
            "Glioma",
            "No Tumor",
            "Pituitary",
            "Meningioma"
        ]
    )

    plt.xlabel(
        "Predicted Class"
    )

    plt.ylabel(
        "Actual Class"
    )

    plt.title(
        "Brain Tumor Classification - Test Set Confusion Matrix"
    )

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            OUTPUT_DIR,
            "confusion_matrix.png"
        ),
        dpi=250
    )

    plt.close()

    print("Confusion matrix saved.")


# ============================================================
# 11. PER-CLASS SPECIFICITY
# ============================================================

def calculate_specificity(
    true_labels,
    predictions
):

    cm = confusion_matrix(
        true_labels,
        predictions
    )

    specificities = {}

    for i, class_name in enumerate(
        CLASS_NAMES
    ):

        true_positive = cm[i, i]

        false_positive = (
            cm[:, i].sum() - true_positive
        )

        false_negative = (
            cm[i, :].sum() - true_positive
        )

        true_negative = (
            cm.sum()
            - true_positive
            - false_positive
            - false_negative
        )

        if (
            true_negative + false_positive
        ) == 0:

            specificity = 0.0

        else:

            specificity = (
                true_negative
                /
                (
                    true_negative
                    + false_positive
                )
            )

        specificities[class_name] = specificity

    print("\n" + "-" * 70)
    print("PER-CLASS SPECIFICITY")
    print("-" * 70)

    for class_name, value in specificities.items():

        print(
            f"{class_name:15s}: {value:.4f}"
        )

    # Save
    with open(
        os.path.join(
            OUTPUT_DIR,
            "specificity.txt"
        ),
        "w"
    ) as f:

        f.write(
            "Per-Class Specificity\n"
        )

        f.write(
            "=" * 40 + "\n"
        )

        for class_name, value in specificities.items():

            f.write(
                f"{class_name}: {value:.4f}\n"
            )

    return specificities


# ============================================================
# 12. SAVE TEST PREDICTIONS
# ============================================================

def save_predictions(
    test_generator,
    true_labels,
    predictions,
    probabilities
):

    print("\nSaving test predictions...")

    filenames = test_generator.filenames

    rows = []

    for i in range(
        len(predictions)
    ):

        true_class = CLASS_NAMES[
            true_labels[i]
        ]

        predicted_class = CLASS_NAMES[
            predictions[i]
        ]

        confidence = float(
            probabilities[i][predictions[i]]
        )

        rows.append({

            "image": filenames[i],

            "actual_class": true_class,

            "predicted_class": predicted_class,

            "confidence": confidence,

            "glioma_probability":
                float(probabilities[i][0]),

            "no_tumor_probability":
                float(probabilities[i][1]),

            "pituitary_probability":
                float(probabilities[i][2]),

            "meningioma_probability":
                float(probabilities[i][3])
        })

    df = pd.DataFrame(rows)

    csv_path = os.path.join(
        OUTPUT_DIR,
        "test_predictions.csv"
    )

    df.to_csv(
        csv_path,
        index=False
    )

    print(
        f"Test predictions saved to:\n{csv_path}"
    )


# ============================================================
# 13. SAVE FINAL MODEL
# ============================================================

def save_final_model(model):

    model_path = os.path.join(
        OUTPUT_DIR,
        "brain_tumor_4class_model.keras"
    )

    model.save(
        model_path
    )

    print(
        f"\nFinal model saved to:\n{model_path}"
    )


# ============================================================
# 14. MAIN
# ============================================================

def main():

    print("\n")
    print("=" * 70)
    print("BRAIN TUMOR DETECTION - 4 CLASS CNN")
    print("=" * 70)

    print("\nClasses:")

    for i, name in enumerate(
        CLASS_NAMES
    ):

        print(
            f"  {i} = {name}"
        )

    # --------------------------------------------------------
    # Check dataset
    # --------------------------------------------------------

    check_dataset()

    # --------------------------------------------------------
    # Create generators
    # --------------------------------------------------------

    train_generator, val_generator, test_generator = (
        create_data_generators()
    )

    # --------------------------------------------------------
    # Build model
    # --------------------------------------------------------

    model, base_model = build_model()

    # --------------------------------------------------------
    # Train
    # --------------------------------------------------------

    history = train_model(
        model,
        base_model,
        train_generator,
        val_generator
    )

    # --------------------------------------------------------
    # Save curves
    # --------------------------------------------------------

    save_training_curves(
        history
    )

    # --------------------------------------------------------
    # Save final model
    # --------------------------------------------------------

    save_final_model(
        model
    )

    # --------------------------------------------------------
    # TEST SET ONLY
    # --------------------------------------------------------

    true_labels, predictions, probabilities = (
        predict_test_set(
            model,
            test_generator
        )
    )

    # --------------------------------------------------------
    # Calculate metrics
    # --------------------------------------------------------

    calculate_metrics(
        true_labels,
        predictions
    )

    # --------------------------------------------------------
    # Specificity
    # --------------------------------------------------------

    calculate_specificity(
        true_labels,
        predictions
    )

    # --------------------------------------------------------
    # Confusion matrix
    # --------------------------------------------------------

    save_confusion_matrix(
        true_labels,
        predictions
    )

    # --------------------------------------------------------
    # Save individual test predictions
    # --------------------------------------------------------

    save_predictions(
        test_generator,
        true_labels,
        predictions,
        probabilities
    )

    # --------------------------------------------------------
    # Finished
    # --------------------------------------------------------

    print("\n" + "=" * 70)
    print("COMPLETE")
    print("=" * 70)

    print("\nTraining:")
    print("  5,600 images")

    print("\nTesting:")
    print("  1,600 images")

    print("\nPredictions:")
    print("  TEST SET ONLY")

    print("\nClasses:")
    print("  Glioma")
    print("  No Tumor")
    print("  Pituitary")
    print("  Meningioma")

    print(
        f"\nAll results saved in:\n{OUTPUT_DIR}"
    )


# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    main()